name: openSUSE build & test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: registry.opensuse.org/opensuse/tumbleweed:latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install devel packages
      run: |
        zypper ref
        zypper --non-interactive in --no-recommends meson gcc libeconf-devel systemd-devel sqlite3-devel audit-devel pam-devel docbook5-xsl-stylesheets

    - name: Setup meson
      run: meson setup build --auto-features=enabled -Db_sanitize=address,undefined

    - name: Compile code
      run: cd build && meson compile

    - name: Run tests
      run: cd build && meson test --verbose --print-errorlogs
